name: Deploy to Azure Web App

on:
  push:
    branches:
      - main # Change this to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Use the version matching your app requirements

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'shoe-ecom'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ${{ github.workspace }}/build
